module.exports = Object.freeze({
  ACTIVITY: 'activity',
  BOOKABLE: 'bookable',
  BOOKABLE_AVAILABILITY_PER_HOTEL: 'bookable_availability_per_hotel',
  BOOKABLE_IN_NEWS: 'bookable_in_news',
  CATEGORY: 'category',
  CLAIMS_AND_SUGGESTIONS: 'claims_and_suggestions',
  DISH: 'dish',
  DISH_AVAILABILITY_PER_HOTEL: 'dish_availability_per_hotel',
  DISH_IN_NEWS: 'dish_in_news',
  EVENT: 'event',
  HOTEL: 'hotel',
  IMAGE: 'image',
  LOCATION: 'location',
  NEWS: 'news',
  NEWS_IN_HOTEL: 'news_in_hotel',
  QUESTION: 'question',
  TIME_OF_ACTIVITY: 'time_of_activity',
  USER: 'user'
})